name = "Ascent Override"
author = "Alex Zero"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faafba2fd78d5781fba5676c548dd9e326327f0f6a146745662adb6a421a50e8"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
