name = "Ascent Override"
author = "Alex Zero"
version = "2.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1636411dba6c87095343ab18543865e997bb53568969c2a16b6252e798964682"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
