name = "Ascent Override"
author = "Alex Zero"
version = "2.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53c835d094d73aeba4e62923d00b09f91a8e7f49b640b529c713ac4d1515a969"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
