name = "Ascent Override"
author = "Alex Zero"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0342fc413d22125047af7be7f6b56db59fcc8712ca7b5cc77af7beac17b35a5"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
