name = "Ascent Override"
author = "Alex Zero"
version = "2.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7171a4d5b9f27da092a8685fd1a8149aed440abf0e70fec1593ed229c76a6880"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
