name = "Ascent Override"
author = "Alex Zero"
version = "2.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "744e66d232a3f1e7ac09df3050ea75d61710bd4187191c3d6b926add3d97be98"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.23"

[options]
acceptable-game-versions = ["1.19.2"]
