name = "Ascent Override"
author = "Alex Zero"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fde898e70ca616c48a9641d86333783142558cd59f685202a019a7280d0fa9e1"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
