name = "Ascent Override"
author = "Alex Zero"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca5e4e3351b4ca32a9cc8bd6c4f2b753bf2a00148e07be004d8da3122d0a246f"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
