removeAnvilXPLimit = true
allowAllEnchantmentCombinations = false
allowAnyEnchantOnAnyItem = true
removeAnvilLevelLimit = false
fairLevelCost = true
removeRepairCostIncrease = true
newAnvilLevelLimit = 255
